all:
	@echo " "
	@echo "valid makefiles are: "
	@echo "   - Makefile.mem_test "
	@echo "   - Makefile.fib      "
	@echo "   - Makefile.opcode   "
	@echo " "
	@echo " targets are:          "
	@echo "    sim                "
	@echo "    gui                "
	@echo "    coverage           "
	@echo "    broken             "
	@echo " "

